// Define your configuration by commenting or uncommenting the following
//  directives, according to what thirdy party packages you have installed.
// This include file assumes that you have first included SBDCompilers.inc .
{$define TntSupport} // Define if you have Troy Wolbrink's TNT controls installed.

{.$define USEJVCL}    // Define if you have Jedi VCL installed.

// ======== End Configuration section ===============
